### ISSUE TITLE
versionCode not increased?

### ISSUE THREAD

**Issue by IzzySoft** [DigitalNutritionalAssessment/gibsonify#54]
Though there are multiple releases available and a `versionName` of 1.2.0 indicating that, `versionCode` is still on `1`. As Android uses `versionCode` to tell versions apart (and to decide whether a given APK is an update to an already installed app), it's important to always increase that right before tagging a new release. Could you please do that for future releases? Thanks in advance!

**Comment by adam-sroka** [comment]
Hi @IzzySoft, thanks a lot for pointing this out! I now had a look at it.

I wasn't super familiar with Android app versioning, and it seems that I introduced this bug [here](https://github.com/DigitalNutritionalAssessment/gibsonify/commit/afc6a3e6c5a0f2685c00e48e11f989f73b77ca68) by specifying the `cz.yaml` config to update the `version` line in the `pubspec.yaml` file to the specified semantic version (e.g. `1.1.0`) upon running `cz bump`.

However, this strips the part after the `+` symbol in the `version` line, which [represents the _build number_ in Flutter and is used to generate the `versionCode`](https://www.flutterbeads.com/update-app-version-in-flutter/). This got first manifested [here](https://github.com/DigitalNutritionalAssessment/gibsonify/commit/8817ba66be9129aab987b1a54548483489fcf7f2#diff-8b7e9df87668ffa6a04b32e1769a33434999e54ae081c52e5d943c541d4c0d25) after updating to version `1.0.0`. Hence the `versionCode` got out of sync and has stayed like that up until now. Just as you say about the `versionCode` (and also [android docs](https://developer.android.com/studio/publish/versioning)):

> The value is a positive integer so that other apps can programmatically evaluate it, for example to check an upgrade or downgrade relationship. You can set the value to any positive integer you want, however you should make sure that each successive release of your app uses a greater value. You cannot upload an APK to the Play Store with a versionCode you have already used for a previous version.

So we need to fix this to be updated (incremented by +1?) when bumping versions. I could have a look if this can be done by some quick change to `cz.yaml`, but since it seems that @fpervaiz is working on some release bump+build CI in #53, @fpervaiz lmk if you want to have a look at it yourself 😊.

**Comment by IzzySoft** [comment]
> So we need to fix this to be updated (incremented by +1?)

By 1 is fine (would then serve as "release counter"). By definition it just has to be larger than anything previously defined, so there are different practices around. Just don't increase it too much as you never could go back then. With +1 you're totally on the safe side.

Never heard this causing issues with an app; for Flutter apps it usually suffices defining it properly in `pubspec.yaml`. But then, I'm no Flutter dev (not even an Android dev) – so I'm totally with you being cautious and asking a team member :smile:

**Comment by fpervaiz** [comment]
@adam-sroka thank you for triaging the issue. I'm happy to pick this up!
